name = "Cyberpunk Neon"
background = "#000000"
foreground = "#00ff00"
border = "#ff00ff"
running = "#00ff9f"
stopped = "#ff0055"
restarting = "#f6ff00"
selection_bg = "#00ff9f"
selection_fg = "#000000"
header_fg = "#f6ff00"
cpu_low = "#00ff9f"
cpu_mid = "#00b8ff"
cpu_high = "#ff0055"
memory_chart = "#bd00ff"
network_rx = "#00b8ff"
network_tx = "#ff0055"
