name = "Dracula (Default)"
background = "#282a36"
foreground = "#f8f8f2"
border = "#6272a4"
running = "#50fa7b"
stopped = "#ff5555"
restarting = "#ffb86c"
selection_bg = "#bd93f9"
selection_fg = "#282a36"
header_fg = "#8be9fd"
cpu_low = "#50fa7b"
cpu_mid = "#ffb86c"
cpu_high = "#ff5555"
memory_chart = "#bd93f9"
network_rx = "#8be9fd"
network_tx = "#ff79c6"
