name = "Gruvbox Dark"
background = "#282828"
foreground = "#ebdbb2"
border = "#928374"
running = "#b8bb26"
stopped = "#fb4934"
restarting = "#fabd2f"
selection_bg = "#d65d0e"
selection_fg = "#282828"
header_fg = "#83a598"
cpu_low = "#b8bb26"
cpu_mid = "#fabd2f"
cpu_high = "#fb4934"
memory_chart = "#d3869b"
network_rx = "#83a598"
network_tx = "#fe8019"
